apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-manual-backups
  namespace: backups
spec:
  template:
    spec:
      containers:
        - name: backup
          image: 402083338966.dkr.ecr.eu-west-1.amazonaws.com/mongo-backups:latest
          envFrom:
            - configMapRef:
                name: mongo-backups-config
            - secretRef:
                name: demacia-mongo
            - secretRef:
                name: aws-credentials  
      restartPolicy: OnFailure
  backoffLimit: 1
