# This is a basic workflow to help you get started with Actions

name: Test on develop push or pull request

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Install-and-test:
    runs-on: ubuntu-latest
    container:
      image: binpar/dockerimages:node12mongo
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.OS }}-node12mongo-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install Modules
        run: npm install
      - name: Audit
        run: npm audit
      - name: Build
        run: npm run build
      - name: Lint
        run: npm run lint
      - name: Test
        run: mongod & npm run test
        env:
          BUCKET_NAME: ${{secrets.BUCKET_NAME}}
