name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Build Docker image and push it to the registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Upload image to ECR
        uses: appleboy/docker-ecr-action@master
        with:
          access_key: ${{ secrets.ACCESS_KEY_ID }}
          secret_key: ${{ secrets.SECRET_ACCESS_KEY }}
          registry: ${{ secrets.REGISTRY }}
          cache_from: ${{ secrets.CACHE }}
          repo: mongo-backups
          region: eu-west-1
          auto_tag: true
          dockerfile: Dockerfile